### ISSUE TITLE
How to use Environment Lights in java?

### ISSUE THREAD

**Issue by fangjunsong** [ThomasGorisse/SceneformMaintained#196]

**Comment by fangjunsong** [comment]
sceneView.environment = HDRLoader.loadEnvironment(
                this@MainActivity,
                "evening_meadow_2k.hdr"
            )
in kotlin like this , is ok;
mARFragment.getArSceneView()._environment =HDREnvironmentKt.loadEnvironment(var5, ARFragmentActivity.this, "evening_meadow_2k.hdr", false,null);
in java like this , is error;

please tell me how to use HDRLoader in java

**Comment by ThomasGorisse** [comment]
Use this one for Java (no coroutine)
https://github.com/ThomasGorisse/SceneformMaintained/blob/master/core/src/main/java/com/gorisse/thomas/sceneform/environment/HDREnvironment.kt#L109-L133
